name: Sync release or hotfix to paywall-api-stage

on:
  push:
    branches:
      - release/*
      - hotfix/*

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup git
        run: |
          git config --global user.email "cecilinabing@gmail.com"
          git config --global user.name "Cecilina"
      - name: Sync when release or hotfix branch is updated
        run: |
          git fetch origin
          git checkout paywall-api-stage
          git merge develop -X theirs
          git push origin paywall-api-stage